// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: certificate.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeeCoinV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeCoinV2) Reset() {
	*x = FeeCoinV2{}
	mi := &file_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeCoinV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeCoinV2) ProtoMessage() {}

func (x *FeeCoinV2) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeCoinV2.ProtoReflect.Descriptor instead.
func (*FeeCoinV2) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *FeeCoinV2) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *FeeCoinV2) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AuthorizationIntentV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Denom         string                 `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AccountNumber uint64                 `protobuf:"varint,6,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence      uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimeoutHeight uint64                 `protobuf:"varint,8,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
	Memo          string                 `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	FeeAmount     []*FeeCoinV2           `protobuf:"bytes,10,rep,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,11,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationIntentV2) Reset() {
	*x = AuthorizationIntentV2{}
	mi := &file_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationIntentV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationIntentV2) ProtoMessage() {}

func (x *AuthorizationIntentV2) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationIntentV2.ProtoReflect.Descriptor instead.
func (*AuthorizationIntentV2) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationIntentV2) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AuthorizationIntentV2) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizationIntentV2) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *AuthorizationIntentV2) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *AuthorizationIntentV2) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AuthorizationIntentV2) GetAccountNumber() uint64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *AuthorizationIntentV2) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuthorizationIntentV2) GetTimeoutHeight() uint64 {
	if x != nil {
		return x.TimeoutHeight
	}
	return 0
}

func (x *AuthorizationIntentV2) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *AuthorizationIntentV2) GetFeeAmount() []*FeeCoinV2 {
	if x != nil {
		return x.FeeAmount
	}
	return nil
}

func (x *AuthorizationIntentV2) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

type AuthorizationCertificateSignDocV2 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Intent           *AuthorizationIntentV2 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	PolicyId         string                 `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion    uint64                 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyHash       []byte                 `protobuf:"bytes,5,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	IssuerSetId      uint64                 `protobuf:"varint,6,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	ValidFromHeight  int64                  `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight int64                  `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizationCertificateSignDocV2) Reset() {
	*x = AuthorizationCertificateSignDocV2{}
	mi := &file_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCertificateSignDocV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCertificateSignDocV2) ProtoMessage() {}

func (x *AuthorizationCertificateSignDocV2) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCertificateSignDocV2.ProtoReflect.Descriptor instead.
func (*AuthorizationCertificateSignDocV2) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizationCertificateSignDocV2) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuthorizationCertificateSignDocV2) GetIntent() *AuthorizationIntentV2 {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *AuthorizationCertificateSignDocV2) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AuthorizationCertificateSignDocV2) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *AuthorizationCertificateSignDocV2) GetPolicyHash() []byte {
	if x != nil {
		return x.PolicyHash
	}
	return nil
}

func (x *AuthorizationCertificateSignDocV2) GetIssuerSetId() uint64 {
	if x != nil {
		return x.IssuerSetId
	}
	return 0
}

func (x *AuthorizationCertificateSignDocV2) GetValidFromHeight() int64 {
	if x != nil {
		return x.ValidFromHeight
	}
	return 0
}

func (x *AuthorizationCertificateSignDocV2) GetValidUntilHeight() int64 {
	if x != nil {
		return x.ValidUntilHeight
	}
	return 0
}

type IssuerSignatureV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerSignatureV2) Reset() {
	*x = IssuerSignatureV2{}
	mi := &file_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerSignatureV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerSignatureV2) ProtoMessage() {}

func (x *IssuerSignatureV2) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerSignatureV2.ProtoReflect.Descriptor instead.
func (*IssuerSignatureV2) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{3}
}

func (x *IssuerSignatureV2) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *IssuerSignatureV2) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AuthorizationCertificateV2 struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	SignDoc       *AuthorizationCertificateSignDocV2 `protobuf:"bytes,1,opt,name=sign_doc,json=signDoc,proto3" json:"sign_doc,omitempty"`
	Signatures    []*IssuerSignatureV2               `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationCertificateV2) Reset() {
	*x = AuthorizationCertificateV2{}
	mi := &file_certificate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationCertificateV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCertificateV2) ProtoMessage() {}

func (x *AuthorizationCertificateV2) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCertificateV2.ProtoReflect.Descriptor instead.
func (*AuthorizationCertificateV2) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationCertificateV2) GetSignDoc() *AuthorizationCertificateSignDocV2 {
	if x != nil {
		return x.SignDoc
	}
	return nil
}

func (x *AuthorizationCertificateV2) GetSignatures() []*IssuerSignatureV2 {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_certificate_proto protoreflect.FileDescriptor

const file_certificate_proto_rawDesc = "" +
	"\n" +
	"\x11certificate.proto\x12\x13alpha.authzattrs.v2\"9\n" +
	"\tFeeCoinV2\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xf0\x02\n" +
	"\x15AuthorizationIntentV2\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x14\n" +
	"\x05denom\x18\x04 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12%\n" +
	"\x0eaccount_number\x18\x06 \x01(\x04R\raccountNumber\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x12%\n" +
	"\x0etimeout_height\x18\b \x01(\x04R\rtimeoutHeight\x12\x12\n" +
	"\x04memo\x18\t \x01(\tR\x04memo\x12=\n" +
	"\n" +
	"fee_amount\x18\n" +
	" \x03(\v2\x1e.alpha.authzattrs.v2.FeeCoinV2R\tfeeAmount\x12\x1b\n" +
	"\tgas_limit\x18\v \x01(\x04R\bgasLimit\"\xe2\x02\n" +
	"!AuthorizationCertificateSignDocV2\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12B\n" +
	"\x06intent\x18\x02 \x01(\v2*.alpha.authzattrs.v2.AuthorizationIntentV2R\x06intent\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vpolicy_hash\x18\x05 \x01(\fR\n" +
	"policyHash\x12\"\n" +
	"\rissuer_set_id\x18\x06 \x01(\x04R\vissuerSetId\x12*\n" +
	"\x11valid_from_height\x18\a \x01(\x03R\x0fvalidFromHeight\x12,\n" +
	"\x12valid_until_height\x18\b \x01(\x03R\x10validUntilHeight\"N\n" +
	"\x11IssuerSignatureV2\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xb7\x01\n" +
	"\x1aAuthorizationCertificateV2\x12Q\n" +
	"\bsign_doc\x18\x01 \x01(\v26.alpha.authzattrs.v2.AuthorizationCertificateSignDocV2R\asignDoc\x12F\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2&.alpha.authzattrs.v2.IssuerSignatureV2R\n" +
	"signaturesB-Z+spaghetti/internal/authorization/pb/v2;v2pbb\x06proto3"

var (
	file_certificate_proto_rawDescOnce sync.Once
	file_certificate_proto_rawDescData []byte
)

func file_certificate_proto_rawDescGZIP() []byte {
	file_certificate_proto_rawDescOnce.Do(func() {
		file_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certificate_proto_rawDesc), len(file_certificate_proto_rawDesc)))
	})
	return file_certificate_proto_rawDescData
}

var file_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_certificate_proto_goTypes = []any{
	(*FeeCoinV2)(nil),                         // 0: alpha.authzattrs.v2.FeeCoinV2
	(*AuthorizationIntentV2)(nil),             // 1: alpha.authzattrs.v2.AuthorizationIntentV2
	(*AuthorizationCertificateSignDocV2)(nil), // 2: alpha.authzattrs.v2.AuthorizationCertificateSignDocV2
	(*IssuerSignatureV2)(nil),                 // 3: alpha.authzattrs.v2.IssuerSignatureV2
	(*AuthorizationCertificateV2)(nil),        // 4: alpha.authzattrs.v2.AuthorizationCertificateV2
}
var file_certificate_proto_depIdxs = []int32{
	0, // 0: alpha.authzattrs.v2.AuthorizationIntentV2.fee_amount:type_name -> alpha.authzattrs.v2.FeeCoinV2
	1, // 1: alpha.authzattrs.v2.AuthorizationCertificateSignDocV2.intent:type_name -> alpha.authzattrs.v2.AuthorizationIntentV2
	2, // 2: alpha.authzattrs.v2.AuthorizationCertificateV2.sign_doc:type_name -> alpha.authzattrs.v2.AuthorizationCertificateSignDocV2
	3, // 3: alpha.authzattrs.v2.AuthorizationCertificateV2.signatures:type_name -> alpha.authzattrs.v2.IssuerSignatureV2
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_certificate_proto_init() }
func file_certificate_proto_init() {
	if File_certificate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_proto_rawDesc), len(file_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_certificate_proto_goTypes,
		DependencyIndexes: file_certificate_proto_depIdxs,
		MessageInfos:      file_certificate_proto_msgTypes,
	}.Build()
	File_certificate_proto = out.File
	file_certificate_proto_goTypes = nil
	file_certificate_proto_depIdxs = nil
}
