// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alpha/authzattrs/v2/certificate.proto

package v2pb

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeCoinV2 struct {
	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *FeeCoinV2) Reset()         { *m = FeeCoinV2{} }
func (m *FeeCoinV2) String() string { return proto.CompactTextString(m) }
func (*FeeCoinV2) ProtoMessage()    {}
func (*FeeCoinV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3b849bd89064bc, []int{0}
}
func (m *FeeCoinV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeCoinV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeCoinV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeCoinV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeCoinV2.Merge(m, src)
}
func (m *FeeCoinV2) XXX_Size() int {
	return m.Size()
}
func (m *FeeCoinV2) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeCoinV2.DiscardUnknown(m)
}

var xxx_messageInfo_FeeCoinV2 proto.InternalMessageInfo

func (m *FeeCoinV2) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FeeCoinV2) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type AuthorizationIntentV2 struct {
	ChainId       string       `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Subject       string       `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Receiver      string       `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Denom         string       `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string       `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AccountNumber uint64       `protobuf:"varint,6,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence      uint64       `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimeoutHeight uint64       `protobuf:"varint,8,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
	Memo          string       `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	FeeAmount     []*FeeCoinV2 `protobuf:"bytes,10,rep,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	GasLimit      uint64       `protobuf:"varint,11,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
}

func (m *AuthorizationIntentV2) Reset()         { *m = AuthorizationIntentV2{} }
func (m *AuthorizationIntentV2) String() string { return proto.CompactTextString(m) }
func (*AuthorizationIntentV2) ProtoMessage()    {}
func (*AuthorizationIntentV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3b849bd89064bc, []int{1}
}
func (m *AuthorizationIntentV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationIntentV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationIntentV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationIntentV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationIntentV2.Merge(m, src)
}
func (m *AuthorizationIntentV2) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationIntentV2) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationIntentV2.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationIntentV2 proto.InternalMessageInfo

func (m *AuthorizationIntentV2) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *AuthorizationIntentV2) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthorizationIntentV2) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *AuthorizationIntentV2) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AuthorizationIntentV2) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *AuthorizationIntentV2) GetAccountNumber() uint64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *AuthorizationIntentV2) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *AuthorizationIntentV2) GetTimeoutHeight() uint64 {
	if m != nil {
		return m.TimeoutHeight
	}
	return 0
}

func (m *AuthorizationIntentV2) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *AuthorizationIntentV2) GetFeeAmount() []*FeeCoinV2 {
	if m != nil {
		return m.FeeAmount
	}
	return nil
}

func (m *AuthorizationIntentV2) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

type AuthorizationCertificateSignDocV2 struct {
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Intent           *AuthorizationIntentV2 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	PolicyId         string                 `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion    uint64                 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyHash       []byte                 `protobuf:"bytes,5,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	IssuerSetId      uint64                 `protobuf:"varint,6,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	ValidFromHeight  int64                  `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight int64                  `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
}

func (m *AuthorizationCertificateSignDocV2) Reset()         { *m = AuthorizationCertificateSignDocV2{} }
func (m *AuthorizationCertificateSignDocV2) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCertificateSignDocV2) ProtoMessage()    {}
func (*AuthorizationCertificateSignDocV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3b849bd89064bc, []int{2}
}
func (m *AuthorizationCertificateSignDocV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationCertificateSignDocV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationCertificateSignDocV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationCertificateSignDocV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCertificateSignDocV2.Merge(m, src)
}
func (m *AuthorizationCertificateSignDocV2) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationCertificateSignDocV2) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCertificateSignDocV2.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCertificateSignDocV2 proto.InternalMessageInfo

func (m *AuthorizationCertificateSignDocV2) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AuthorizationCertificateSignDocV2) GetIntent() *AuthorizationIntentV2 {
	if m != nil {
		return m.Intent
	}
	return nil
}

func (m *AuthorizationCertificateSignDocV2) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *AuthorizationCertificateSignDocV2) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *AuthorizationCertificateSignDocV2) GetPolicyHash() []byte {
	if m != nil {
		return m.PolicyHash
	}
	return nil
}

func (m *AuthorizationCertificateSignDocV2) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *AuthorizationCertificateSignDocV2) GetValidFromHeight() int64 {
	if m != nil {
		return m.ValidFromHeight
	}
	return 0
}

func (m *AuthorizationCertificateSignDocV2) GetValidUntilHeight() int64 {
	if m != nil {
		return m.ValidUntilHeight
	}
	return 0
}

type IssuerSignatureV2 struct {
	IssuerId  string `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *IssuerSignatureV2) Reset()         { *m = IssuerSignatureV2{} }
func (m *IssuerSignatureV2) String() string { return proto.CompactTextString(m) }
func (*IssuerSignatureV2) ProtoMessage()    {}
func (*IssuerSignatureV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3b849bd89064bc, []int{3}
}
func (m *IssuerSignatureV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IssuerSignatureV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IssuerSignatureV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IssuerSignatureV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerSignatureV2.Merge(m, src)
}
func (m *IssuerSignatureV2) XXX_Size() int {
	return m.Size()
}
func (m *IssuerSignatureV2) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerSignatureV2.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerSignatureV2 proto.InternalMessageInfo

func (m *IssuerSignatureV2) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *IssuerSignatureV2) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AuthorizationCertificateV2 struct {
	SignDoc    *AuthorizationCertificateSignDocV2 `protobuf:"bytes,1,opt,name=sign_doc,json=signDoc,proto3" json:"sign_doc,omitempty"`
	Signatures []*IssuerSignatureV2               `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *AuthorizationCertificateV2) Reset()         { *m = AuthorizationCertificateV2{} }
func (m *AuthorizationCertificateV2) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCertificateV2) ProtoMessage()    {}
func (*AuthorizationCertificateV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3b849bd89064bc, []int{4}
}
func (m *AuthorizationCertificateV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationCertificateV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationCertificateV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationCertificateV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCertificateV2.Merge(m, src)
}
func (m *AuthorizationCertificateV2) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationCertificateV2) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCertificateV2.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCertificateV2 proto.InternalMessageInfo

func (m *AuthorizationCertificateV2) GetSignDoc() *AuthorizationCertificateSignDocV2 {
	if m != nil {
		return m.SignDoc
	}
	return nil
}

func (m *AuthorizationCertificateV2) GetSignatures() []*IssuerSignatureV2 {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeCoinV2)(nil), "alpha.authzattrs.v2.FeeCoinV2")
	proto.RegisterType((*AuthorizationIntentV2)(nil), "alpha.authzattrs.v2.AuthorizationIntentV2")
	proto.RegisterType((*AuthorizationCertificateSignDocV2)(nil), "alpha.authzattrs.v2.AuthorizationCertificateSignDocV2")
	proto.RegisterType((*IssuerSignatureV2)(nil), "alpha.authzattrs.v2.IssuerSignatureV2")
	proto.RegisterType((*AuthorizationCertificateV2)(nil), "alpha.authzattrs.v2.AuthorizationCertificateV2")
}

func init() {
	proto.RegisterFile("alpha/authzattrs/v2/certificate.proto", fileDescriptor_eb3b849bd89064bc)
}

var fileDescriptor_eb3b849bd89064bc = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xee, 0x26, 0x69, 0x7e, 0x4e, 0x5a, 0xb5, 0xe3, 0x0f, 0x6b, 0x95, 0xb5, 0x06, 0x2a, 0xa5,
	0x4a, 0x02, 0x2b, 0x08, 0x22, 0x5e, 0xb4, 0xd5, 0xd2, 0x80, 0x14, 0xdc, 0x62, 0x2e, 0xbc, 0x59,
	0x26, 0xbb, 0x27, 0xd9, 0x91, 0xec, 0x4c, 0xdc, 0x99, 0x5d, 0xb0, 0x4f, 0xe1, 0xdb, 0xf8, 0x0a,
	0x5e, 0xf6, 0xd2, 0x4b, 0x49, 0x5f, 0xc0, 0x47, 0x90, 0x99, 0xd9, 0xfc, 0x88, 0x11, 0xef, 0xe6,
	0x7c, 0xe7, 0xdb, 0x73, 0xbe, 0xfd, 0xbe, 0x61, 0x60, 0x9f, 0x4e, 0xa6, 0x09, 0xed, 0xd1, 0x5c,
	0x25, 0x97, 0x54, 0xa9, 0x4c, 0xf6, 0x0a, 0xbf, 0x17, 0x61, 0xa6, 0xd8, 0x88, 0x45, 0x54, 0x61,
	0x77, 0x9a, 0x09, 0x25, 0xc8, 0x6d, 0x43, 0xeb, 0x2e, 0x69, 0xdd, 0xc2, 0xef, 0xbc, 0x84, 0xd6,
	0x29, 0xe2, 0x89, 0x60, 0x7c, 0xe0, 0x93, 0x3b, 0xb0, 0x19, 0x23, 0x17, 0xa9, 0xeb, 0xec, 0x39,
	0x07, 0xad, 0xc0, 0x16, 0xe4, 0x1e, 0xd4, 0x69, 0x2a, 0x72, 0xae, 0xdc, 0x8a, 0x81, 0xcb, 0xaa,
	0xf3, 0xab, 0x02, 0x77, 0x8f, 0x72, 0x95, 0x88, 0x8c, 0x5d, 0x52, 0xc5, 0x04, 0xef, 0x73, 0x85,
	0x5c, 0x0d, 0x7c, 0x72, 0x1f, 0x9a, 0x51, 0x42, 0x19, 0x0f, 0x59, 0x5c, 0x8e, 0x6a, 0x98, 0xba,
	0x1f, 0x13, 0x17, 0x1a, 0x32, 0x1f, 0x7e, 0xc2, 0x68, 0x3e, 0x6d, 0x5e, 0x92, 0x5d, 0x68, 0x66,
	0x18, 0x21, 0x2b, 0x30, 0x73, 0xab, 0xa6, 0xb5, 0xa8, 0x97, 0xc2, 0x6a, 0xeb, 0x85, 0x6d, 0xae,
	0x0a, 0x23, 0xfb, 0x70, 0x83, 0x46, 0x91, 0x3e, 0x86, 0x3c, 0x4f, 0x87, 0x98, 0xb9, 0xf5, 0x3d,
	0xe7, 0xa0, 0x16, 0x6c, 0x97, 0xe8, 0xb9, 0x01, 0xf5, 0x42, 0x89, 0x9f, 0x73, 0xe4, 0x11, 0xba,
	0x0d, 0x43, 0x58, 0xd4, 0x7a, 0x84, 0x62, 0x29, 0x8a, 0x5c, 0x85, 0x09, 0xb2, 0x71, 0xa2, 0xdc,
	0xa6, 0x1d, 0x51, 0xa2, 0x67, 0x06, 0x24, 0x04, 0x6a, 0x29, 0xa6, 0xc2, 0x6d, 0x99, 0xfd, 0xe6,
	0x4c, 0x5e, 0x03, 0x8c, 0x10, 0xc3, 0x52, 0x19, 0xec, 0x55, 0x0f, 0xda, 0xbe, 0xd7, 0x5d, 0xe3,
	0x7d, 0x77, 0x61, 0x7c, 0xd0, 0x1a, 0x21, 0x1e, 0x59, 0xf1, 0x0f, 0xa0, 0x35, 0xa6, 0x32, 0x9c,
	0xb0, 0x94, 0x29, 0xb7, 0x6d, 0x65, 0x8d, 0xa9, 0x7c, 0xa7, 0xeb, 0xce, 0xac, 0x02, 0x8f, 0xff,
	0xb0, 0xfc, 0x64, 0x99, 0xf2, 0x05, 0x1b, 0xf3, 0x37, 0x22, 0x1a, 0xf8, 0xda, 0x97, 0x58, 0xa4,
	0x94, 0xf1, 0xd2, 0xfc, 0xb2, 0x22, 0xc7, 0x50, 0x67, 0x26, 0x22, 0x63, 0x7d, 0xdb, 0x3f, 0x5c,
	0xab, 0x6a, 0x6d, 0xa4, 0x41, 0xf9, 0xa5, 0x96, 0x37, 0x15, 0x13, 0x16, 0x7d, 0xd1, 0xd9, 0x96,
	0x31, 0x59, 0xa0, 0x1f, 0x6b, 0xd7, 0xca, 0x66, 0x81, 0x99, 0x64, 0x82, 0x9b, 0xbc, 0x6a, 0xc1,
	0xb6, 0x45, 0x07, 0x16, 0x24, 0x8f, 0xa0, 0x5d, 0xd2, 0x12, 0x2a, 0x13, 0x13, 0xde, 0x56, 0x00,
	0x16, 0x3a, 0xa3, 0x32, 0x21, 0x1d, 0xd8, 0x66, 0x52, 0xe6, 0x98, 0x85, 0x12, 0x95, 0x5e, 0x64,
	0xf3, 0x6b, 0x5b, 0xf0, 0x02, 0x55, 0x3f, 0x26, 0x87, 0xb0, 0x53, 0xd0, 0x09, 0x8b, 0xc3, 0x51,
	0x26, 0xd2, 0x79, 0x48, 0x3a, 0xc6, 0x6a, 0x70, 0xd3, 0x34, 0x4e, 0x33, 0x91, 0x96, 0x31, 0x3d,
	0x03, 0x62, 0xb9, 0x39, 0x57, 0x6c, 0xb2, 0x9a, 0x68, 0x35, 0xb8, 0x65, 0x3a, 0x1f, 0x74, 0xc3,
	0xb2, 0x3b, 0xe7, 0xb0, 0xd3, 0xb7, 0x8b, 0xd8, 0x98, 0x53, 0x95, 0x67, 0x38, 0xf0, 0xf5, 0x7f,
	0x97, 0x92, 0x16, 0x77, 0xba, 0x69, 0x81, 0x7e, 0x4c, 0x1e, 0x42, 0x4b, 0xce, 0xb9, 0xc6, 0xdb,
	0xad, 0x60, 0x09, 0x74, 0xbe, 0x39, 0xb0, 0xfb, 0xaf, 0xd0, 0x06, 0x3e, 0x79, 0x0f, 0x4d, 0xcd,
	0x0d, 0x63, 0x11, 0x99, 0xc1, 0x6d, 0xff, 0xc5, 0xff, 0x73, 0x59, 0x97, 0x7b, 0xd0, 0x90, 0xf6,
	0x48, 0x4e, 0x01, 0x16, 0xeb, 0xa5, 0x5b, 0x31, 0x57, 0xf0, 0xc9, 0xda, 0xa1, 0x7f, 0xfd, 0x68,
	0xb0, 0xf2, 0xe5, 0xf1, 0xdb, 0xef, 0x33, 0xcf, 0xb9, 0x9a, 0x79, 0xce, 0xcf, 0x99, 0xe7, 0x7c,
	0xbd, 0xf6, 0x36, 0xae, 0xae, 0xbd, 0x8d, 0x1f, 0xd7, 0xde, 0xc6, 0xc7, 0xa7, 0x72, 0x4a, 0xc7,
	0x09, 0x2a, 0xc5, 0x7a, 0xfa, 0x62, 0x64, 0x9c, 0x4e, 0xcc, 0xfb, 0xb3, 0x10, 0xd8, 0x9b, 0x0e,
	0x7b, 0x85, 0xff, 0xaa, 0xf0, 0xa7, 0xc3, 0x61, 0xdd, 0xbc, 0x3f, 0xcf, 0x7f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xd9, 0x73, 0xc3, 0x68, 0xa8, 0x04, 0x00, 0x00,
}

func (m *FeeCoinV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeCoinV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeCoinV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationIntentV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationIntentV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationIntentV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GasLimit != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x58
	}
	if len(m.FeeAmount) > 0 {
		for iNdEx := len(m.FeeAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCertificate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TimeoutHeight != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.TimeoutHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Sequence != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x38
	}
	if m.AccountNumber != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.AccountNumber))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationCertificateSignDocV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationCertificateSignDocV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationCertificateSignDocV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidUntilHeight != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.ValidUntilHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidFromHeight != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.ValidFromHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PolicyHash) > 0 {
		i -= len(m.PolicyHash)
		copy(dAtA[i:], m.PolicyHash)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.PolicyHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintCertificate(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Intent != nil {
		{
			size, err := m.Intent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCertificate(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IssuerSignatureV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IssuerSignatureV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IssuerSignatureV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintCertificate(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationCertificateV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationCertificateV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationCertificateV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCertificate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.SignDoc != nil {
		{
			size, err := m.SignDoc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCertificate(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCertificate(dAtA []byte, offset int, v uint64) int {
	offset -= sovCertificate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeCoinV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	return n
}

func (m *AuthorizationIntentV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	if m.AccountNumber != 0 {
		n += 1 + sovCertificate(uint64(m.AccountNumber))
	}
	if m.Sequence != 0 {
		n += 1 + sovCertificate(uint64(m.Sequence))
	}
	if m.TimeoutHeight != 0 {
		n += 1 + sovCertificate(uint64(m.TimeoutHeight))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	if len(m.FeeAmount) > 0 {
		for _, e := range m.FeeAmount {
			l = e.Size()
			n += 1 + l + sovCertificate(uint64(l))
		}
	}
	if m.GasLimit != 0 {
		n += 1 + sovCertificate(uint64(m.GasLimit))
	}
	return n
}

func (m *AuthorizationCertificateSignDocV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	if m.Intent != nil {
		l = m.Intent.Size()
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovCertificate(uint64(m.PolicyVersion))
	}
	l = len(m.PolicyHash)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	if m.IssuerSetId != 0 {
		n += 1 + sovCertificate(uint64(m.IssuerSetId))
	}
	if m.ValidFromHeight != 0 {
		n += 1 + sovCertificate(uint64(m.ValidFromHeight))
	}
	if m.ValidUntilHeight != 0 {
		n += 1 + sovCertificate(uint64(m.ValidUntilHeight))
	}
	return n
}

func (m *IssuerSignatureV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovCertificate(uint64(l))
	}
	return n
}

func (m *AuthorizationCertificateV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignDoc != nil {
		l = m.SignDoc.Size()
		n += 1 + l + sovCertificate(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovCertificate(uint64(l))
		}
	}
	return n
}

func sovCertificate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCertificate(x uint64) (n int) {
	return sovCertificate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeCoinV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeCoinV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeCoinV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCertificate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertificate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationIntentV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationIntentV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationIntentV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumber", wireType)
			}
			m.AccountNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			m.TimeoutHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeAmount = append(m.FeeAmount, &FeeCoinV2{})
			if err := m.FeeAmount[len(m.FeeAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCertificate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertificate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationCertificateSignDocV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationCertificateSignDocV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationCertificateSignDocV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Intent == nil {
				m.Intent = &AuthorizationIntentV2{}
			}
			if err := m.Intent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyHash = append(m.PolicyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PolicyHash == nil {
				m.PolicyHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFromHeight", wireType)
			}
			m.ValidFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidFromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilHeight", wireType)
			}
			m.ValidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCertificate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertificate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IssuerSignatureV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IssuerSignatureV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IssuerSignatureV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCertificate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertificate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationCertificateV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationCertificateV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationCertificateV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignDoc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SignDoc == nil {
				m.SignDoc = &AuthorizationCertificateSignDocV2{}
			}
			if err := m.SignDoc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertificate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertificate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, &IssuerSignatureV2{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCertificate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertificate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCertificate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCertificate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCertificate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCertificate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCertificate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCertificate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCertificate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCertificate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCertificate = fmt.Errorf("proto: unexpected end of group")
)
