// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: authorization.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankSendConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankSendConstraints) Reset() {
	*x = BankSendConstraints{}
	mi := &file_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankSendConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankSendConstraints) ProtoMessage() {}

func (x *BankSendConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankSendConstraints.ProtoReflect.Descriptor instead.
func (*BankSendConstraints) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *BankSendConstraints) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *BankSendConstraints) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *BankSendConstraints) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

type AuthorizationRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId     string                 `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Subject             string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	MsgTypeUrl          string                 `protobuf:"bytes,3,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	PolicyId            string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion       uint64                 `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	IssuerSetId         uint64                 `protobuf:"varint,6,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	ValidFromHeight     int64                  `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight    int64                  `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
	Revoked             bool                   `protobuf:"varint,9,opt,name=revoked,proto3" json:"revoked,omitempty"`
	BankSendConstraints *BankSendConstraints   `protobuf:"bytes,10,opt,name=bank_send_constraints,json=bankSendConstraints,proto3" json:"bank_send_constraints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizationRecord) Reset() {
	*x = AuthorizationRecord{}
	mi := &file_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRecord) ProtoMessage() {}

func (x *AuthorizationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRecord.ProtoReflect.Descriptor instead.
func (*AuthorizationRecord) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationRecord) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *AuthorizationRecord) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizationRecord) GetMsgTypeUrl() string {
	if x != nil {
		return x.MsgTypeUrl
	}
	return ""
}

func (x *AuthorizationRecord) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AuthorizationRecord) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *AuthorizationRecord) GetIssuerSetId() uint64 {
	if x != nil {
		return x.IssuerSetId
	}
	return 0
}

func (x *AuthorizationRecord) GetValidFromHeight() int64 {
	if x != nil {
		return x.ValidFromHeight
	}
	return 0
}

func (x *AuthorizationRecord) GetValidUntilHeight() int64 {
	if x != nil {
		return x.ValidUntilHeight
	}
	return 0
}

func (x *AuthorizationRecord) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *AuthorizationRecord) GetBankSendConstraints() *BankSendConstraints {
	if x != nil {
		return x.BankSendConstraints
	}
	return nil
}

type AuthorizationBatchSignDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BatchId       uint64                 `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyHash    []byte                 `protobuf:"bytes,6,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	IssuerSetId   uint64                 `protobuf:"varint,7,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	Records       []*AuthorizationRecord `protobuf:"bytes,8,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationBatchSignDoc) Reset() {
	*x = AuthorizationBatchSignDoc{}
	mi := &file_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationBatchSignDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationBatchSignDoc) ProtoMessage() {}

func (x *AuthorizationBatchSignDoc) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationBatchSignDoc.ProtoReflect.Descriptor instead.
func (*AuthorizationBatchSignDoc) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizationBatchSignDoc) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuthorizationBatchSignDoc) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AuthorizationBatchSignDoc) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *AuthorizationBatchSignDoc) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AuthorizationBatchSignDoc) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *AuthorizationBatchSignDoc) GetPolicyHash() []byte {
	if x != nil {
		return x.PolicyHash
	}
	return nil
}

func (x *AuthorizationBatchSignDoc) GetIssuerSetId() uint64 {
	if x != nil {
		return x.IssuerSetId
	}
	return 0
}

func (x *AuthorizationBatchSignDoc) GetRecords() []*AuthorizationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type BatchSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSignature) Reset() {
	*x = BatchSignature{}
	mi := &file_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSignature) ProtoMessage() {}

func (x *BatchSignature) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSignature.ProtoReflect.Descriptor instead.
func (*BatchSignature) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSignature) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *BatchSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AuthorizationBatch struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SignDoc       *AuthorizationBatchSignDoc `protobuf:"bytes,1,opt,name=sign_doc,json=signDoc,proto3" json:"sign_doc,omitempty"`
	Signatures    []*BatchSignature          `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationBatch) Reset() {
	*x = AuthorizationBatch{}
	mi := &file_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationBatch) ProtoMessage() {}

func (x *AuthorizationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationBatch.ProtoReflect.Descriptor instead.
func (*AuthorizationBatch) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationBatch) GetSignDoc() *AuthorizationBatchSignDoc {
	if x != nil {
		return x.SignDoc
	}
	return nil
}

func (x *AuthorizationBatch) GetSignatures() []*BatchSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type MsgBatchUpsertAuthorizations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitter     string                 `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Batch         *AuthorizationBatch    `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBatchUpsertAuthorizations) Reset() {
	*x = MsgBatchUpsertAuthorizations{}
	mi := &file_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBatchUpsertAuthorizations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBatchUpsertAuthorizations) ProtoMessage() {}

func (x *MsgBatchUpsertAuthorizations) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBatchUpsertAuthorizations.ProtoReflect.Descriptor instead.
func (*MsgBatchUpsertAuthorizations) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *MsgBatchUpsertAuthorizations) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *MsgBatchUpsertAuthorizations) GetBatch() *AuthorizationBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type MsgBatchUpsertAuthorizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBatchUpsertAuthorizationsResponse) Reset() {
	*x = MsgBatchUpsertAuthorizationsResponse{}
	mi := &file_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBatchUpsertAuthorizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBatchUpsertAuthorizationsResponse) ProtoMessage() {}

func (x *MsgBatchUpsertAuthorizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBatchUpsertAuthorizationsResponse.ProtoReflect.Descriptor instead.
func (*MsgBatchUpsertAuthorizationsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{6}
}

var File_authorization_proto protoreflect.FileDescriptor

const file_authorization_proto_rawDesc = "" +
	"\n" +
	"\x13authorization.proto\x12\x13alpha.authzattrs.v1\"f\n" +
	"\x13BankSendConstraints\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\"\xb6\x03\n" +
	"\x13AuthorizationRecord\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12 \n" +
	"\fmsg_type_url\x18\x03 \x01(\tR\n" +
	"msgTypeUrl\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\x04R\rpolicyVersion\x12\"\n" +
	"\rissuer_set_id\x18\x06 \x01(\x04R\vissuerSetId\x12*\n" +
	"\x11valid_from_height\x18\a \x01(\x03R\x0fvalidFromHeight\x12,\n" +
	"\x12valid_until_height\x18\b \x01(\x03R\x10validUntilHeight\x12\x18\n" +
	"\arevoked\x18\t \x01(\bR\arevoked\x12\\\n" +
	"\x15bank_send_constraints\x18\n" +
	" \x01(\v2(.alpha.authzattrs.v1.BankSendConstraintsR\x13bankSendConstraints\"\xb6\x02\n" +
	"\x19AuthorizationBatchSignDoc\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\x04R\abatchId\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vpolicy_hash\x18\x06 \x01(\fR\n" +
	"policyHash\x12\"\n" +
	"\rissuer_set_id\x18\a \x01(\x04R\vissuerSetId\x12B\n" +
	"\arecords\x18\b \x03(\v2(.alpha.authzattrs.v1.AuthorizationRecordR\arecords\"K\n" +
	"\x0eBatchSignature\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xa4\x01\n" +
	"\x12AuthorizationBatch\x12I\n" +
	"\bsign_doc\x18\x01 \x01(\v2..alpha.authzattrs.v1.AuthorizationBatchSignDocR\asignDoc\x12C\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2#.alpha.authzattrs.v1.BatchSignatureR\n" +
	"signatures\"{\n" +
	"\x1cMsgBatchUpsertAuthorizations\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\tR\tsubmitter\x12=\n" +
	"\x05batch\x18\x02 \x01(\v2'.alpha.authzattrs.v1.AuthorizationBatchR\x05batch\"&\n" +
	"$MsgBatchUpsertAuthorizationsResponseB%Z#spaghetti/internal/authorization/pbb\x06proto3"

var (
	file_authorization_proto_rawDescOnce sync.Once
	file_authorization_proto_rawDescData []byte
)

func file_authorization_proto_rawDescGZIP() []byte {
	file_authorization_proto_rawDescOnce.Do(func() {
		file_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)))
	})
	return file_authorization_proto_rawDescData
}

var file_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authorization_proto_goTypes = []any{
	(*BankSendConstraints)(nil),                  // 0: alpha.authzattrs.v1.BankSendConstraints
	(*AuthorizationRecord)(nil),                  // 1: alpha.authzattrs.v1.AuthorizationRecord
	(*AuthorizationBatchSignDoc)(nil),            // 2: alpha.authzattrs.v1.AuthorizationBatchSignDoc
	(*BatchSignature)(nil),                       // 3: alpha.authzattrs.v1.BatchSignature
	(*AuthorizationBatch)(nil),                   // 4: alpha.authzattrs.v1.AuthorizationBatch
	(*MsgBatchUpsertAuthorizations)(nil),         // 5: alpha.authzattrs.v1.MsgBatchUpsertAuthorizations
	(*MsgBatchUpsertAuthorizationsResponse)(nil), // 6: alpha.authzattrs.v1.MsgBatchUpsertAuthorizationsResponse
}
var file_authorization_proto_depIdxs = []int32{
	0, // 0: alpha.authzattrs.v1.AuthorizationRecord.bank_send_constraints:type_name -> alpha.authzattrs.v1.BankSendConstraints
	1, // 1: alpha.authzattrs.v1.AuthorizationBatchSignDoc.records:type_name -> alpha.authzattrs.v1.AuthorizationRecord
	2, // 2: alpha.authzattrs.v1.AuthorizationBatch.sign_doc:type_name -> alpha.authzattrs.v1.AuthorizationBatchSignDoc
	3, // 3: alpha.authzattrs.v1.AuthorizationBatch.signatures:type_name -> alpha.authzattrs.v1.BatchSignature
	4, // 4: alpha.authzattrs.v1.MsgBatchUpsertAuthorizations.batch:type_name -> alpha.authzattrs.v1.AuthorizationBatch
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_authorization_proto_init() }
func file_authorization_proto_init() {
	if File_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authorization_proto_goTypes,
		DependencyIndexes: file_authorization_proto_depIdxs,
		MessageInfos:      file_authorization_proto_msgTypes,
	}.Build()
	File_authorization_proto = out.File
	file_authorization_proto_goTypes = nil
	file_authorization_proto_depIdxs = nil
}
