// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// il login e la gestione delle room
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // es. "login ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequest) Reset() {
	*x = RoomListRequest{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequest) ProtoMessage() {}

func (x *RoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequest.ProtoReflect.Descriptor instead.
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIds       []string               `protobuf:"bytes,1,rep,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *RoomListResponse) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Position
	//	*Packet_Login
	//	*Packet_LoginResponse
	//	*Packet_CreateRoom
	//	*Packet_CreateRoomResponse
	//	*Packet_JoinRoom
	//	*Packet_JoinRoomResponse
	//	*Packet_RoomListRequest
	//	*Packet_RoomListResponse
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *Packet) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetPosition() *Position {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *Packet) GetLogin() *LoginRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *Packet) GetLoginResponse() *LoginResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginResponse); ok {
			return x.LoginResponse
		}
	}
	return nil
}

func (x *Packet) GetCreateRoom() *CreateRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

func (x *Packet) GetCreateRoomResponse() *CreateRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoomResponse); ok {
			return x.CreateRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetJoinRoom() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomResponse() *JoinRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomResponse); ok {
			return x.JoinRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetRoomListRequest() *RoomListRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomListRequest); ok {
			return x.RoomListRequest
		}
	}
	return nil
}

func (x *Packet) GetRoomListResponse() *RoomListResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomListResponse); ok {
			return x.RoomListResponse
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Position struct {
	Position *Position `protobuf:"bytes,3,opt,name=position,proto3,oneof"`
}

type Packet_Login struct {
	Login *LoginRequest `protobuf:"bytes,4,opt,name=login,proto3,oneof"`
}

type Packet_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,5,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type Packet_CreateRoom struct {
	CreateRoom *CreateRoomRequest `protobuf:"bytes,6,opt,name=create_room,json=createRoom,proto3,oneof"`
}

type Packet_CreateRoomResponse struct {
	CreateRoomResponse *CreateRoomResponse `protobuf:"bytes,7,opt,name=create_room_response,json=createRoomResponse,proto3,oneof"`
}

type Packet_JoinRoom struct {
	JoinRoom *JoinRoomRequest `protobuf:"bytes,8,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Packet_JoinRoomResponse struct {
	JoinRoomResponse *JoinRoomResponse `protobuf:"bytes,9,opt,name=join_room_response,json=joinRoomResponse,proto3,oneof"`
}

type Packet_RoomListRequest struct {
	RoomListRequest *RoomListRequest `protobuf:"bytes,10,opt,name=room_list_request,json=roomListRequest,proto3,oneof"`
}

type Packet_RoomListResponse struct {
	RoomListResponse *RoomListResponse `protobuf:"bytes,11,opt,name=room_list_response,json=roomListResponse,proto3,oneof"`
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Position) isPacket_Msg() {}

func (*Packet_Login) isPacket_Msg() {}

func (*Packet_LoginResponse) isPacket_Msg() {}

func (*Packet_CreateRoom) isPacket_Msg() {}

func (*Packet_CreateRoomResponse) isPacket_Msg() {}

func (*Packet_JoinRoom) isPacket_Msg() {}

func (*Packet_JoinRoomResponse) isPacket_Msg() {}

func (*Packet_RoomListRequest) isPacket_Msg() {}

func (*Packet_RoomListResponse) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"*\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"F\n" +
	"\rLoginResponse\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"a\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"_\n" +
	"\x10JoinRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x11\n" +
	"\x0fRoomListRequest\"-\n" +
	"\x10RoomListResponse\x12\x19\n" +
	"\broom_ids\x18\x01 \x03(\tR\aroomIds\"\xa0\x05\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x11.packets.PositionH\x00R\bposition\x12-\n" +
	"\x05login\x18\x04 \x01(\v2\x15.packets.LoginRequestH\x00R\x05login\x12?\n" +
	"\x0elogin_response\x18\x05 \x01(\v2\x16.packets.LoginResponseH\x00R\rloginResponse\x12=\n" +
	"\vcreate_room\x18\x06 \x01(\v2\x1a.packets.CreateRoomRequestH\x00R\n" +
	"createRoom\x12O\n" +
	"\x14create_room_response\x18\a \x01(\v2\x1b.packets.CreateRoomResponseH\x00R\x12createRoomResponse\x127\n" +
	"\tjoin_room\x18\b \x01(\v2\x18.packets.JoinRoomRequestH\x00R\bjoinRoom\x12I\n" +
	"\x12join_room_response\x18\t \x01(\v2\x19.packets.JoinRoomResponseH\x00R\x10joinRoomResponse\x12F\n" +
	"\x11room_list_request\x18\n" +
	" \x01(\v2\x18.packets.RoomListRequestH\x00R\x0froomListRequest\x12I\n" +
	"\x12room_list_response\x18\v \x01(\v2\x19.packets.RoomListResponseH\x00R\x10roomListResponseB\x05\n" +
	"\x03msgB\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_packets_proto_goTypes = []any{
	(*ChatMessage)(nil),        // 0: packets.ChatMessage
	(*IdMessage)(nil),          // 1: packets.IdMessage
	(*Position)(nil),           // 2: packets.Position
	(*LoginRequest)(nil),       // 3: packets.LoginRequest
	(*LoginResponse)(nil),      // 4: packets.LoginResponse
	(*CreateRoomRequest)(nil),  // 5: packets.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 6: packets.CreateRoomResponse
	(*JoinRoomRequest)(nil),    // 7: packets.JoinRoomRequest
	(*JoinRoomResponse)(nil),   // 8: packets.JoinRoomResponse
	(*RoomListRequest)(nil),    // 9: packets.RoomListRequest
	(*RoomListResponse)(nil),   // 10: packets.RoomListResponse
	(*Packet)(nil),             // 11: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	0,  // 0: packets.Packet.chat:type_name -> packets.ChatMessage
	2,  // 1: packets.Packet.position:type_name -> packets.Position
	3,  // 2: packets.Packet.login:type_name -> packets.LoginRequest
	4,  // 3: packets.Packet.login_response:type_name -> packets.LoginResponse
	5,  // 4: packets.Packet.create_room:type_name -> packets.CreateRoomRequest
	6,  // 5: packets.Packet.create_room_response:type_name -> packets.CreateRoomResponse
	7,  // 6: packets.Packet.join_room:type_name -> packets.JoinRoomRequest
	8,  // 7: packets.Packet.join_room_response:type_name -> packets.JoinRoomResponse
	9,  // 8: packets.Packet.room_list_request:type_name -> packets.RoomListRequest
	10, // 9: packets.Packet.room_list_response:type_name -> packets.RoomListResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[11].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Position)(nil),
		(*Packet_Login)(nil),
		(*Packet_LoginResponse)(nil),
		(*Packet_CreateRoom)(nil),
		(*Packet_CreateRoomResponse)(nil),
		(*Packet_JoinRoom)(nil),
		(*Packet_JoinRoomResponse)(nil),
		(*Packet_RoomListRequest)(nil),
		(*Packet_RoomListResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
